version: "3"
services:
  irc1:
    build: ./
    expose:
      - 6667

  irc2:
    build: ./
    expose:
      - 6667

  haproxy:
    image: haproxy:2.2.20-alpine3.15
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy
    ports:
      - "6667:6667"
      - "8404:8404"
    links:
      - irc1
      - irc2